import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import MarketingLayout from "../components/MarketingLayout.jsx";

const POLICY_EMAIL = "policies@nomorae.com";
const EFFECTIVE_DATE = "27 April 2026";

function SectionHeading({ children, id }) {
  return (
    <h2 id={id} className="mt-10 text-2xl font-bold text-[#0F172A]">
      {children}
    </h2>
  );
}

function SubHeading({ children }) {
  return <h3 className="mt-6 text-lg font-semibold text-[#0F172A]">{children}</h3>;
}

function Paragraph({ children }) {
  return <p className="mt-3 text-sm leading-6 text-slate-700">{children}</p>;
}

function Bullets({ items }) {
  return (
    <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700 list-disc list-inside">
      {items.map((item, idx) => (
        <li key={idx}>{item}</li>
      ))}
    </ul>
  );
}

export default function Terms() {
  useEffect(() => {
    document.title = "Nomorae | Terms and Conditions";
  }, []);

  return (
    <MarketingLayout enableDemoButton>
      <div className="mx-auto max-w-4xl px-4 sm:px-6 py-12 sm:py-16">
        <div className="rounded-3xl border border-brand-200/90 bg-gradient-to-b from-white to-brand-50 p-6 sm:p-10">
          <span className="rounded-full border border-brand-200/90 bg-brand-50 px-4 py-2 text-xs font-semibold text-[#14532d]">
            Effective {EFFECTIVE_DATE}
          </span>
          <h1 className="mt-6 text-4xl font-bold tracking-tight text-[#0F172A]">Terms and Conditions</h1>
          <p className="mt-3 text-slate-600 max-w-2xl">
            These Terms and Conditions (the &quot;Terms&quot;) govern your access to and use of the Nomorae
            website, applications, and AI-assisted legal productivity services (collectively, the
            &quot;Service&quot;). By creating an account or using the Service you agree to these Terms.
          </p>
        </div>

        <div className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 sm:p-10">
          <SectionHeading id="acceptance">1. Acceptance of these Terms</SectionHeading>
          <Paragraph>
            These Terms form a binding agreement between you (the &quot;Customer&quot;, &quot;you&quot;) and Nomorae
            (&quot;Nomorae&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;). If you are using the Service on
            behalf of a legal practice, firm, business, or other organisation, you represent and warrant that
            you have authority to bind that organisation to these Terms, and references to &quot;you&quot; include
            both you personally and that organisation. If you do not agree to these Terms, you must not use
            the Service.
          </Paragraph>

          <SectionHeading id="definitions">2. Definitions</SectionHeading>
          <Bullets
            items={[
              '"POPIA" means the Protection of Personal Information Act, 4 of 2013 of the Republic of South Africa.',
              '"Customer Content" means documents, files, prompts, notes, matter records, templates, and any other data uploaded or generated by you or your authorised users in the Service.',
              '"AI Output" means content generated by the Service using machine learning models in response to your prompts or content, including drafts, summaries, classifications, and search results.',
              '"Subscription" means a paid plan that grants access to the Service for a specified billing period and seat count.',
              '"Workspace" means an account namespace shared by you and your authorised users.',
            ]}
          />

          <SectionHeading id="accounts">3. Accounts and access</SectionHeading>
          <Bullets
            items={[
              "You must provide accurate registration details and keep your credentials confidential. You are responsible for activity carried out under your account.",
              "Workspace owners are responsible for inviting, suspending, and removing users, and for ensuring their authorised users comply with these Terms.",
              "You must notify us promptly at policies@nomorae.com if you suspect any unauthorised access to your account.",
              "We may suspend or terminate accounts that breach these Terms, our acceptable use rules, or applicable law.",
            ]}
          />

          <SectionHeading id="subscriptions">4. Subscriptions, billing, and incentive credits</SectionHeading>
          <Paragraph>
            Paid features of the Service are provided on a Subscription basis. Pricing, plan inclusions, seat
            limits, AI quotas, and any incentive AI credits are described on our pricing page or in the order
            confirmation. By subscribing, you authorise us (and our payment processor PayFast) to charge the
            applicable fees on a recurring basis until the Subscription is cancelled.
          </Paragraph>
          <Bullets
            items={[
              "Subscriptions renew automatically for the same billing cycle unless cancelled before the next renewal date.",
              "We may grant discretionary incentive AI credits when you start or renew a Subscription. These credits are not redeemable for cash and may expire on cancellation or downgrade.",
              "We may run a daily reconciliation against PayFast to confirm subscription status. If a Subscription is found to be cancelled, lapsed, or otherwise inactive, the Workspace may be moved to the free tier and paid features may become unavailable.",
              "Fees are inclusive or exclusive of VAT as indicated at the time of purchase. You are responsible for any taxes that apply in your jurisdiction.",
              "Except where required by law, fees are non-refundable. If you believe a charge is incorrect, contact us at policies@nomorae.com within 30 days.",
            ]}
          />

          <SubHeading>4.1 Cancellation and downgrades</SubHeading>
          <Paragraph>
            You may cancel your Subscription at any time from the billing area of the Service. Cancellation
            takes effect at the end of the current billing cycle; you will retain access to paid features
            until then. We do not provide pro-rated refunds for partial billing cycles.
          </Paragraph>

          <SectionHeading id="acceptable-use">5. Acceptable use</SectionHeading>
          <Paragraph>You agree not to:</Paragraph>
          <Bullets
            items={[
              "Use the Service for any unlawful, infringing, defamatory, harassing, or fraudulent purpose.",
              "Upload Customer Content that you do not have the right to upload, or that infringes the rights of any third party.",
              "Attempt to reverse engineer, decompile, scrape, or circumvent any security or rate-limiting measures of the Service.",
              "Use the Service to develop a competing product or to train machine learning models that would compete with the Service.",
              "Interfere with the integrity or performance of the Service, including by introducing malware, sending unsolicited communications via the Service, or attempting to gain unauthorised access.",
              "Use the Service to provide regulated legal advice to end clients without the necessary professional qualifications and supervision required in your jurisdiction.",
            ]}
          />

          <SectionHeading id="customer-content">6. Customer Content and AI Output</SectionHeading>
          <Paragraph>
            You retain all ownership rights in your Customer Content. You grant Nomorae a limited,
            non-exclusive, worldwide licence to host, copy, transmit, and process Customer Content as
            reasonably required to provide the Service to you and your authorised users, including by sending
            relevant excerpts to AI providers used to generate AI Output.
          </Paragraph>
          <Paragraph>
            AI Output is generated automatically and may be inaccurate, incomplete, or misleading. AI Output
            is not legal advice and should not be relied upon as a substitute for the judgement of a
            qualified legal professional. You are responsible for reviewing, verifying, and editing all AI
            Output before relying on it, sharing it with clients, or filing it with any tribunal or authority.
          </Paragraph>
          <Paragraph>
            We do not authorise AI providers to use your Customer Content to train their general-purpose
            foundation models, where the provider supports such an option.
          </Paragraph>

          <SectionHeading id="confidentiality">7. Confidentiality and privacy</SectionHeading>
          <Paragraph>
            We treat Customer Content as confidential and process it in accordance with our{" "}
            <Link to="/privacy" className="text-[#16A34A] hover:underline">
              Privacy Policy
            </Link>
            . In respect of personal information contained in Customer Content, Nomorae acts as an
            &quot;Operator&quot; for purposes of POPIA and processes such personal information only on your
            documented instructions and as required by law. You acknowledge that you remain the
            &quot;Responsible Party&quot; for that personal information and are responsible for complying with
            POPIA when collecting, using, and sharing it.
          </Paragraph>

          <SectionHeading id="intellectual-property">8. Intellectual property</SectionHeading>
          <Paragraph>
            The Service, including all software, models, designs, logos, and underlying technology, is owned
            by Nomorae or its licensors and is protected by intellectual property laws. Except for the
            limited rights expressly granted to you in these Terms, no rights are transferred to you. Any
            feedback you provide may be used by Nomorae without obligation.
          </Paragraph>

          <SectionHeading id="third-parties">9. Third-party services</SectionHeading>
          <Paragraph>
            The Service relies on third-party providers, including PayFast for payments, our cloud and
            infrastructure providers, our email delivery providers, and one or more AI model providers. Use
            of those services may be subject to their own terms. We are not responsible for the acts or
            omissions of third-party providers, but we will use reasonable efforts to select reputable
            providers and to monitor their performance.
          </Paragraph>

          <SectionHeading id="warranties">10. Warranties and disclaimers</SectionHeading>
          <Paragraph>
            We will provide the Service with reasonable skill and care. To the maximum extent permitted by
            law, the Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis, without
            warranties of any kind, whether express or implied, including warranties of merchantability,
            fitness for a particular purpose, accuracy, or non-infringement. We do not warrant that the
            Service or AI Output will be uninterrupted, error-free, or that it will produce particular legal
            outcomes.
          </Paragraph>

          <SectionHeading id="liability">11. Limitation of liability</SectionHeading>
          <Paragraph>
            To the maximum extent permitted by law, neither party will be liable for any indirect,
            incidental, special, consequential, exemplary, or punitive damages, including loss of profits,
            loss of revenue, loss of data, loss of goodwill, or business interruption, even if advised of the
            possibility of such damages.
          </Paragraph>
          <Paragraph>
            Each party&apos;s aggregate liability arising out of or in connection with these Terms or the
            Service, whether in contract, delict (tort), or otherwise, will not exceed the total fees paid by
            you to Nomorae for the Service in the twelve (12) months immediately preceding the event giving
            rise to the claim.
          </Paragraph>
          <Paragraph>
            Nothing in these Terms limits or excludes liability for fraud, gross negligence, wilful
            misconduct, or any liability that cannot be excluded under applicable law (including liability
            under the Consumer Protection Act, 68 of 2008, where it applies).
          </Paragraph>

          <SectionHeading id="indemnity">12. Indemnity</SectionHeading>
          <Paragraph>
            You agree to indemnify and hold Nomorae and its directors, employees, and operators harmless from
            and against any claims, damages, losses, and reasonable costs (including legal fees) arising out
            of or in connection with: (a) your Customer Content; (b) your use of the Service in breach of
            these Terms or applicable law; or (c) any reliance on AI Output without appropriate review by a
            qualified legal professional.
          </Paragraph>

          <SectionHeading id="term">13. Term and termination</SectionHeading>
          <Paragraph>
            These Terms apply from the date you first access the Service and continue until terminated. Either
            party may terminate the agreement for material breach if the breach is not remedied within 14 days
            of written notice. We may suspend or terminate access immediately if continued access poses a
            security, legal, or reputational risk.
          </Paragraph>
          <Paragraph>
            On termination, your right to use the Service ends. We will, on written request received within 30
            days of termination, make a reasonable effort to allow you to export your Customer Content. After
            this period, we may delete Customer Content in accordance with our retention policy.
          </Paragraph>

          <SectionHeading id="governing-law">14. Governing law and dispute resolution</SectionHeading>
          <Paragraph>
            These Terms are governed by the laws of the Republic of South Africa. The parties submit to the
            non-exclusive jurisdiction of the High Court of South Africa. The parties will use reasonable
            efforts to resolve disputes informally before commencing formal proceedings; nothing in this
            clause prevents either party from seeking urgent or interim relief.
          </Paragraph>

          <SectionHeading id="changes">15. Changes to the Service or these Terms</SectionHeading>
          <Paragraph>
            We may update the Service and these Terms from time to time. Material changes will be
            communicated by posting the updated Terms on this page and, where appropriate, by email or
            in-product notice. Continued use of the Service after the effective date of the updated Terms
            constitutes acceptance of the changes.
          </Paragraph>

          <SectionHeading id="general">16. General</SectionHeading>
          <Bullets
            items={[
              "If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.",
              "These Terms (together with the Privacy Policy and any order form) constitute the entire agreement between you and Nomorae regarding the Service and supersede prior or contemporaneous agreements on the subject.",
              "A failure or delay in enforcing any right under these Terms is not a waiver of that right.",
              "You may not assign these Terms without our prior written consent. We may assign these Terms to a successor in connection with a merger, acquisition, or sale of substantially all of our assets.",
              "Notices to Nomorae under these Terms must be sent to policies@nomorae.com.",
            ]}
          />

          <SectionHeading id="contact">17. Contact us</SectionHeading>
          <Paragraph>
            For any questions about these Terms, please email{" "}
            <a className="text-[#16A34A] hover:underline" href={`mailto:${POLICY_EMAIL}`}>
              {POLICY_EMAIL}
            </a>
            .
          </Paragraph>

          <div className="mt-10 flex flex-wrap gap-3">
            <Link to="/privacy" className="btn-secondary rounded-xl px-5 py-3 text-sm font-semibold">
              Read our Privacy Policy
            </Link>
            <Link to="/security" className="btn-secondary rounded-xl px-5 py-3 text-sm font-semibold">
              Security overview
            </Link>
            <Link to="/register" className="btn-primary rounded-xl px-5 py-3 text-sm font-semibold">
              Get started
            </Link>
          </div>
        </div>
      </div>
    </MarketingLayout>
  );
}
